### ISSUE TITLE
Create developper documentation

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/makemyflix#17]
For geting more developpers to start working on this code we should provide developper documentation and give instructions how to run this sofware in local configuration.

**Comment by EnnoMeijers** [comment]
@aabelmann Thanks for updating the developer documentation, this helps a lot! Would it be possible to run a local setup also with a local storage instead of an S3 bucket? This could lower the barrier for noobs like me that are not very familiar with S3 configuration.

**Comment by aabelmann** [comment]
@EnnoMeijers We can but I'm worried it would cause for more confusion.

The way we have set it up now, is that docker-compose will setup a S3 bucket (using minio) and if you use .env.example as your own .env file, you should be able to start without any extra configuration. (if that isn't the case, please let me know)

To clarify Minio is running a S3 bucket locally, so it's also writing to your local storage.
In our case the folder called "minio-data", which contains all the files you uploaded.

If you do want to run it without a S3 bucket, the following needs to be done:
- Remove the Minio (and related) entries from the docker-compose.override.yml
- Update .env to not have any S3 / Minio variables
- Update Strapi's plugins.js to not use aws-s3

This will make Strapi write directly to the folder "public/upload".

Adding this as an option to the current setup would make the configuration more complicated and convoluted.
And since it doesn't really offer a benefit, I would prefer to not add it.

**Comment by EnnoMeijers** [comment]
Ah, thanks for the clarification, based on the technical requirements section my impression was that an AWS-S3 bucket needed to be created before starting the docker container. I will do some more testing and come back to it.

**Comment by EnnoMeijers** [comment]
Looking good now, closing this issue!
